server.port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/boonkuaeboonsutta/Documents/Learning/elk-kafka/Hand-On-Project/config-repo
  security:
    user:
      name: ${CONFIG_SERVER_USR}
      password: ${CONFIG_SERVER_PWD}


#
#  spring.security.user.name=root
#  spring.security.user.password=s3cr3t

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info


---
spring.profiles: docker
spring.cloud.config.server.native.searchLocations: file:/config-repo

